services:
  
  postgres:
    image: postgres:latest
    container_name: jobmarket_postgres
    volumes:
      - ./persistant_data/postgres_data:/var/lib/postgresql/data
      - ./persistant_data/logs/postgres:/var/log/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=feb24

  transform:
    image: transform_app:0.0.1
    container_name: jobmarket_transform
    volumes:
      - ./persistant_data/data:/transform_app/data
      - ./persistant_data/logs/transform:/var/log/transform
    environment:
      - POSTGRES_DBNAME=jobmarket
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=feb24
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - LOGFILE=/var/log/transform/log.txt 
    command: ["bash"]
    stdin_open: true
    tty: true

  data_retrieval:
    image: data_retrieval_app:0.0.1
    container_name: jobmarket_data_retrieval
    volumes:
      - ./persistant_data/data/data_retrieval:/data_retrieval_app/data/
      - ./persistant_data/logs/data_retrieval:/var/log/data_retrieval
    environment:
      - PATH_DATA_RAW=/data_retrieval_app/data/raw_data
      - PATH_DATA_PROCESSED=/data_retrieval_app/data/processed_data
      - DIR_NAME_MUSE=muse.com
      - DIR_NAME_REED=reed.co.uk
      - KNOWN_CURRENCY=['$', '£', '€']
      - DIR_NAME_OKJOB=okjob.io
      - OKJOB_API_KEY=AIzaSyDErRezqW2klWRYKwQkzuOIMGJ5AeD5GSY
      - REED_API_KEY=52f1eba3-39f1-4ee8-bc36-26140b349e67
      - API_VERSION_REED=1.0
      - LOGFILE=/var/log/data_retrieval/log.txt
    command: ["bash"]
    stdin_open: true
    tty: true