version: '3'

services:

  jobmarket_db:
    container_name: jobmarket_db_container
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./src/postgres:/docker-entrypoint-initdb.d # create the database at the 1st start

  jobmarket_data_retrieval:
    build:
      context: .
      dockerfile: ./src/data_retrieval/Dockerfile
    container_name: jobmarket_data_retrieval_container
    image: jobmarket_data_retrieval_app:latest
    environment:
      PATH_DATA_RAW: ${PATH_DATA_RAW}
      PATH_DATA_PROCESSED: ${PATH_DATA_PROCESSED}
      DIR_NAME_MUSE: ${DIR_NAME_MUSE}
      DIR_NAME_REED: ${DIR_NAME_REED}
      KNOWN_CURRENCY: ${KNOWN_CURRENCY}
      DIR_NAME_OKJOB: ${DIR_NAME_OKJOB}
      OKJOB_API_KEY: ${OKJOB_API_KEY}
      REED_API_KEY: ${REED_API_KEY}
      API_VERSION_REED: ${API_VERSION_REED}
      LOGFILE: ${LOGFILE_DATA_RETRIEVAL}
      PIPELINE_ACTION: ${PIPELINE_ACTION}
      s: ${s:-}
      e: ${e:-}
      l: ${l:-}
    volumes:
      - ./data:/data_retrieval_app/data
    entrypoint: ["sh", "-c", "python main.py $PIPELINE_ACTION -s=$s -e=$e -l=$l"]

  jobmarket_transform:
    build:
      context: .
      dockerfile: ./src/transform/Dockerfile
    container_name: jobmarket_transform_container
    image: jobmarket_transform_app:latest
    environment:
      PATH_DATA_PROCESSED: ${PATH_DATA_PROCESSED}
      DIR_NAME_MUSE: ${DIR_NAME_MUSE}
      DIR_NAME_REED: ${DIR_NAME_REED}
      DIR_NAME_OKJOB: ${DIR_NAME_OKJOB}
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      LOGFILE: ${LOGFILE_TRANSFORM}
    volumes:
      - ./data:/transform_app/data
    entrypoint: ["sh", "-c", "python main.py"]
    depends_on:
      - jobmarket_db

  jobmarket_model:
    build:
      context: .
      dockerfile: ./src/model_creation/Dockerfile
    container_name: jobmarket_model_container
    image: jobmarket_model_app:latest
    environment:
      PATH_MODEL: /model_app/data/model
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      LOGFILE: ${LOGFILE_MODEL_CREATION}
    volumes:
      - ./data:/model_app/data
    entrypoint: ["sh", "-c", "python main.py"]
    depends_on:
      - jobmarket_db

  jobmarket_api:
    build:
      context: .
      dockerfile: ./src/api/Dockerfile
    container_name: jobmarket_api_container
    image: api_app:latest
    environment:
      PATH_MODEL: /api_app/data/model
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      LOGFILE: ${LOGFILE_API}
      UVICORN_PORT: ${UVICORN_PORT}
    ports:
      - "8000:8000"
    volumes:
      - ./data:/api_app/data
    depends_on:
      - jobmarket_db
